# Generated by Django 5.2.2 on 2025-06-07 10:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_of_case', models.CharField(choices=[('autopsy', 'Autopsy'), ('toxicology', 'Toxicology'), ('histology', 'Histology'), ('other', 'Other')], max_length=50)),
                ('current_status', models.CharField(default='Pending Initial Examination', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RFIDTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('assigned', 'Assigned'), ('damaged', 'Damaged')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_uid', models.CharField(help_text='Unique Body Identifier', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, help_text='Name of the deceased, if known', max_length=255, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodies', to='management.case')),
                ('rfid_tag', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body', to='management.rfidtag')),
            ],
        ),
    ]
