# Generated by Django 5.2.2 on 2025-06-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='autopsy_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='autopsy_notes',
            field=models.TextField(blank=True, help_text='General notes from the autopsy', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='cause_of_death_preliminary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='pathologist_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
