# Generated by Django 5.2.2 on 2025-06-07 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_case_autopsy_date_case_autopsy_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='autopsy_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='autopsy_notes',
        ),
        migrations.RemoveField(
            model_name='case',
            name='cause_of_death_preliminary',
        ),
        migrations.RemoveField(
            model_name='case',
            name='pathologist_name',
        ),
        migrations.CreateModel(
            name='AutopsyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopsy_date', models.DateField(blank=True, null=True)),
                ('pathologist_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cause_of_death_preliminary', models.TextField(blank=True, null=True)),
                ('autopsy_notes', models.TextField(blank=True, help_text='General notes from the autopsy', null=True)),
                ('external_examination_summary', models.TextField(blank=True, help_text='Summary of external examination findings.', null=True)),
                ('internal_examination_summary', models.TextField(blank=True, help_text='Summary of internal examination findings (organ systems).', null=True)),
                ('toxicology_specimens_taken', models.TextField(blank=True, help_text='Details of toxicology specimens taken (e.g., blood, urine, vitreous).', null=True)),
                ('histology_specimens_taken', models.TextField(blank=True, help_text='Details of histology specimens taken (e.g., tissue samples).', null=True)),
                ('date_report_generated', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_finalized', models.BooleanField(default=False, help_text='Is this report finalized?')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autopsy_report', to='management.case')),
                ('report_finalized_by', models.ForeignKey(blank=True, help_text='User who finalized the report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_autopsy_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
