# Generated by Django 5.2.2 on 2025-06-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_case_autopsy_date_remove_case_autopsy_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='dental_records_ref',
            field=models.CharField(blank=True, help_text='Reference/path to dental records', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='body',
            name='dha_id_number',
            field=models.CharField(blank=True, help_text='SA ID number received from DHA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='body',
            name='dha_identification_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted to DHA'), ('PENDING_DHA', 'Pending DHA Response'), ('IDENTIFIED', 'DHA Identified'), ('NO_MATCH', 'DHA No Match Found'), ('MULTIPLE_MATCHES', 'DHA Multiple Potential Matches')], default='NOT_SUBMITTED', help_text='Status of DHA identification process', max_length=20),
        ),
        migrations.AddField(
            model_name='body',
            name='dha_response_notes',
            field=models.TextField(blank=True, help_text='Notes regarding the DHA identification response', null=True),
        ),
        migrations.AddField(
            model_name='body',
            name='dna_sample_id',
            field=models.CharField(blank=True, help_text='ID for DNA sample taken', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='body',
            name='fingerprint_scan_ref',
            field=models.CharField(blank=True, help_text='Reference/path to fingerprint scan file', max_length=255, null=True),
        ),
    ]
