# Generated by Django 5.2.2 on 2025-06-07 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_body_dental_records_ref_body_dha_id_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToxicologyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimens_received', models.TextField(blank=True, help_text='e.g., Blood, Urine, Liver tissue', null=True)),
                ('date_specimens_received', models.DateField(blank=True, null=True)),
                ('requested_by', models.CharField(blank=True, help_text='Name of Pathologist or SAPS officer', max_length=255, null=True)),
                ('analysis_requested', models.TextField(blank=True, help_text='e.g., Screen for common drugs of abuse, alcohol', null=True)),
                ('findings_summary', models.TextField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('toxicologist_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_final', models.BooleanField(default=False, help_text='Is this the final report?')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toxicology_reports', to='management.case')),
            ],
        ),
    ]
